title: My "First" Webpage
theme:  minima 
author: Anonymous
email: ribtom16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome Earthlings....
 I see that you've found your way to the "First" webpage or maybe just a page that surely strives to incorporate a little bit of me..
 I also understand that you've been intrigued to question or just curious to know why this is my "First" Webpage.
 An answer to that will follow a not-so-short shortstory dating a few years back.
 To be "enlightened" with that "shortstory", please wait for the upcoming updates.
# social links
instagram_username: ribtom
Github_username:  Riantom # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
